### ISSUE TITLE
When subissue is a human task, it not open a new Process

### ISSUE THREAD

**Issue by victorlcampos** [visagio/redmine_bpm_integration#17]
Hi,
I have a process that has subprocesses. In this case, I use a issue to open they. But there is a validation in code that desallow it.

` after_commit :start_process_instance, if: 'self.tracker.is_bpm_process? and !self.is_human_task?', on: :create
`

This is realy necessary?

**Comment by lucasarnaud** [comment]
It is necessary. Otherwise it would create a new process instance for each user task in the process.

**Comment by victorlcampos** [comment]
I opened a PR with suggestion to fix both cases
